  module dactylis
  {
      typedef sequence<octet> OctetSeq;

      exception CertNotFound {};

      interface CertificateStore
      {
        OctetSeq getEncCert(in string userId)
          raises (CertNotFound);
      };
  };
